#!/usr/bin/env bash
KITSUNE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
KITSUNE_CLC="${KITSUNE_DIR}/lib/clc/clc"


source "./src/main.bash"
source "./src/template.bash"


declare -pf kitsune

for key in "${!__ks_template[@]}"; do
  __ks_template[${key}]=$("${KITSUNE_CLC}" --escape "${__ks_template[${key}]}")
done

for name in "${!__ks_@}"; do
  declare -p "${name}"
done

printf '
if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
  if [ $# -eq 0 ]; then
    kitsune ps1 --render
  else
    kitsune "${@}"
  fi
elif [ $# -gt 0 ]; then
  kitsune "${@}"
fi
'
